#!/bin/bash

rm /srv/SWIRLnet/data/cyclone/*

var=$(python3.6 /srv/SWIRLnet/dev/check.py)

if [ "$var" == "True" ]; then

ftp -n ftp2.bom.gov.au << END
user ftp your_name@your_e-mail_address
cd anon/gen/fwo/
binary
newer IDQ65248.zip /srv/SWIRLnet/data/cyclone/IDQ65248.zip
newer IDQ65249.zip /srv/SWIRLnet/data/cyclone/IDQ65249.zip
newer IDQ65250.zip /srv/SWIRLnet/data/cyclone/IDQ65250.zip
newer IDD65409.zip /srv/SWIRLnet/data/cyclone/IDD65409.zip

newer IDD65401.zip /srv/SWIRLnet/data/cyclone/IDD65401.zip
newer IDD65402.zip /srv/SWIRLnet/data/cyclone/IDD65402.zip
newer IDQ65251.zip /srv/SWIRLnet/data/cyclone/IDQ65251.zip
newer IDW60283.zip /srv/SWIRLnet/data/cyclone/IDW60283.zip

newer IDW60266.zip /srv/SWIRLnet/data/cyclone/IDW60266.zip
newer IDW60267.zip /srv/SWIRLnet/data/cyclone/IDW60267.zip
newer IDW60268.zip /srv/SWIRLnet/data/cyclone/IDW60268.zip
newer IDD65408.zip /srv/SWIRLnet/data/cyclone/IDD65408.zip
quit

END

cd '/srv/SWIRLnet/data/cyclone'

unzip -o IDQ65248.zip
unzip -o IDQ65249.zip
unzip -o IDQ65250.zip
unzip -o IDD65409.zip

unzip -o IDD65401.zip
unzip -o IDD65402.zip
unzip -o IDQ65251.zip
unzip -o IDW60283.zip

unzip -o IDW60266.zip
unzip -o IDW60268.zip
unzip -o IDW60269.zip
unzip -o IDD65408.zip

NAME="IDW60266"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDD65401"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDQ65248"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDW60267"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDD65402"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDQ65249"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDW60268"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDQ65251"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDQ65250"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDD65408"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDW60283"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*
NAME="IDD65409"
zip ${NAME}.areas.zip ${NAME}.areas.*
zip ${NAME}.fix.zip ${NAME}.fix.*
zip ${NAME}.track.zip ${NAME}.track.*
zip ${NAME}.windarea.zip ${NAME}.windarea.*

fi